### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by emersion** [ultramega/elementary#1]
I would like to translate this app un French. How can I do?

Thanks :-)

**Comment by ultramega** [comment]
The app has been updated to be fully translatable. I created a Wiki page describing how to translate the app into your language: https://github.com/ultramega/elementary/wiki/Translations

Sorry about the long delay in response. There were many changes that needed to be made to allow i18n.

**Comment by Poussinou** [comment]
Hi guys,

I can also contribute to the french translation ;)

@emersion Je te propose qu'on se coordonne, je peux traduire le texte vers lundi ou mardi prochain et tu le relis derrière pour me donner ton avis en ouvrant un nouveau sujet dans "issue" dans mon propre fork avant de le publier, si tu peux le faire avant, alors fait le et moi même j'irais relire et je ferais la même chose dans le "issue" de ton fork à toi ;)

Dis moi si t'es d'accord :)
