### ISSUE TITLE
Translations needed

### ISSUE THREAD

**Issue by ultramega** [ultramega/elementary#14]
I need translations for the following  new string resources:

``` xml
    <string name="prefTitleSubtextValue">Block Value</string>
    <string name="prefSummarySubtextValue">The value to display under the element symbol</string>
    <string name="prefTitleShowControls">Periodic Table Controls</string>
    <string name="prefSummaryShowControls">Show the controls for the Periodic Table in the Table View</string>
```

Languages needed:
- [x] French
- [ ] German
- [x] Italian
- [x] Brazilian Portuguese
- [x] Spanish

**Comment by ultramega** [comment]
@C4R2T3N @rapgenic @Poussinou

**Comment by ghost** [comment]
```
<string name="prefTitleSubtextValue">Valor de Bloque</string>
<string name="prefSummarySubtextValue">Valor a mostrar bajo el símbolo del elemento</string>
<string name="prefTitleShowControls">Controles de Tabla Periódica</string>
<string name="prefSummaryShowControls">Mostrar los controles de Tabla Periódica en la Vista de Tabla</string>
```

**Comment by ultramega** [comment]
@jerefeltan Is that Spanish?

**Comment by ghost** [comment]
Sorry. Yes, it is Spanish.

**Comment by ultramega** [comment]
Thanks. The rest of the Spanish translations were done by Google, so if you see anything that needs corrections please let me know.

**Comment by ultramega** [comment]
#15 #16 #17

**Comment by ultramega** [comment]
Version 0.6.1 is getting released tomorrow. I used Google to get the German translations, so that will have to do if I don't get translations by then. It's the last chance to make any corrections.
