### ISSUE TITLE
Table of solubility

### ISSUE THREAD

**Issue by ghost** [ultramega/elementary#18]
Is possible add a table of solubility?

**Comment by ultramega** [comment]
Can you show an example?

**Comment by ghost** [comment]
![screenshot_2016-11-30-07-50-20](https://cloud.githubusercontent.com/assets/22004671/20742770/94b45e82-b6d2-11e6-86f0-a5939835ca85.png)
![screenshot_2016-11-30-07-48-44](https://cloud.githubusercontent.com/assets/22004671/20742775/9b7b8ede-b6d2-11e6-8db2-7eb3cf4f6ba8.png)

**Comment by ghost** [comment]
The idea came to me by an app of the Play Store .. then I've loaded the screenshots

**Comment by ultramega** [comment]
That seems to be out of the scope of Elementary. I want to keep the app simple and lightweight.
