### ISSUE TITLE
Translation wiki to russian and names correction

### ISSUE THREAD

**Issue by ashed** [ultramega/elementary#26]
I've checked this nomenclature with iupac recommendations.
Some chemical elements changed it's names.
[http://www.chem.qmul.ac.uk/iupac/AtWt/table.html]

**Correct this values please.**

<string name="el113">Ununtrium</string> - **Nihonium**
[https://en.wikipedia.org/wiki/Nihonium]

<string name="el115">Ununpentium</string> - **Moscovium**
[https://en.wikipedia.org/wiki/Moscovium]

<string name="el117">Ununseptium</string> - **Tennessine**
[https://en.wikipedia.org/wiki/Tennessine]

<string name="el118">Ununoctium</string> - **Oganesson**
[https://en.wikipedia.org/wiki/Oganesson]

[https://en.wikipedia.org/wiki/Periodic_table]

[values-ru.zip](https://github.com/ultramega/elementary/files/706606/values-ru.zip)

**Comment by ultramega** [comment]
Thanks for pointing out the error in the wiki. The names have been updated.

**Comment by ultramega** [comment]
Can you also translate the [store description](https://github.com/ultramega/elementary/wiki/Translations#store-description)?

**Comment by ashed** [comment]
[title]
Elementary: периодическая таблица

[keywords]
Science
Chemistry
Elements
Periodic Table

[short-description]
Периодическая таблица элементов с  открытыми исходными кодами. 

[description]
Периодическая таблица элементов с  открытыми исходными кодами.

Особенности:
- масштабируемая периодическая таблица элементов
-  нажмите на элемент для получения базовой информации
- лёгкий доступ к Wikipedia и YouTube видео в описании элемента
- бесплатно и без рекламы!

видео  предоставляется Periodic Videos (http://www.periodicvideos.com/)

Лицензия The MIT License
Исходные коды доступны: https://github.com/ultramega/elementary

Twitter: https://twitter.com/ultramegasoft
Facebook: https://www.facebook.com/ultramegasoft
Google+: https://plus.google.com/+UltraMegaSoftware

**Comment by ashed** [comment]
Translated store.txt

**Comment by ultramega** [comment]
Are the keywords meant to be in English?

**Comment by ashed** [comment]
[keywords]
Наука
Химия
Элементы
Периодическая таблица
Периодическая система Менделеева
Таблица Менделеева
Менделеев

**Comment by ultramega** [comment]
I think that covers everything. Thanks for the contribution.
