### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [ultramega/elementary#27]
Hi @ultramega 

I found [this app ](https://play.google.com/store/apps/details?id=com.periodic_table.periodic_table) on the Google Play Store. This guy just took the source code and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under MIT license and this guy is violating this license;
* He is falsely claiming he made the app;

**Comment by Poussinou** [comment]
@ultramega There are also [this one](https://play.google.com/store/apps/details?id=com.ssaurel.ptable) and [this one](https://play.google.com/store/apps/details?id=com.ssaurel.ptable.pro)
One of them has ads in it, and the other one is payable...

**Comment by stevotvr** [comment]
Thanks for letting me know. I sent a takedown request since they didn't include the copyright notice..

**Comment by stevotvr** [comment]
I finally received a response:

> Hello,
> 
> Thanks for reaching out to us.
> 
> With regard to the following URLs:
> 
> https://play.google.com/store/apps/details?id=com.periodic_table.periodic_table
> 
> The material in question has been found to violate our policies, and we are working to remove it from our services.
> 
> 
> Regards,
> The Google Team

**Comment by Poussinou** [comment]
@ultramega 

[This app](https://play.google.com/store/apps/details?id=com.ssaurel.ptable) and also [this one](https://play.google.com/store/apps/details?id=com.ssaurel.ptable.pro) look a lot like Elementary.
Are they old versions of Elementary? If this is the case, please report them using the DMCA formular that I already provided.

**Comment by stevotvr** [comment]
Thanks for the tip. I sent another request.

**Comment by Poussinou** [comment]
@ultramega 

An other one [here](https://play.google.com/store/apps/details?id=com.ultramegatech.cjc3). It's an old version...

**Comment by stevotvr** [comment]
I don't think that one is based on Elementary.

**Comment by Poussinou** [comment]
The visuals from the Play Store aren't the same as the app. Download the app and have a look ;)

**Comment by stevotvr** [comment]
Alright I looked at it closer and submitted it for removal.

**Comment by stevotvr** [comment]
I received this in response to the DMCA request for the apps referenced in https://github.com/ultramega/elementary/issues/27#issuecomment-331726466. I'm trying to get them to explain this decision.

> Hello,
> 
> Thanks for reaching out to us.
> 
> At this time, Google has decided not to take action. We encourage you to resolve any disputes directly with the individual who posted the content.
> 
> If you cannot reach an agreement and choose to pursue legal action against the individual who posted the content, and that action results in a judicial determination that the material is illegal or should be removed, please send us the court order seeking removal. If you would like to request identifying information about an anonymous poster, please contact google-legal-support@google.com (if you are in the U.S.) or internationalcivil@google.com (if you are outside of the U.S.) for more information on how to serve us with valid legal process.
> 
> Regards,
> The Google Team

**Comment by stevotvr** [comment]
Same response for https://github.com/ultramega/elementary/issues/27#issuecomment-332551938

**Comment by Poussinou** [comment]
Thanks for trying to get an explanation about this decision!
It'll be usefull for me.

Maybe it's my fault. I reported so many stolen apps that Google had to react because they were getting too much DMCA takedown request ... I guess this decision is made to deter open-source app developers from reporting apps as it will become very complicated.

I will contact the free software associations of my country.

Thanks again! :)

**Comment by stevotvr** [comment]
I sent an email to "JesusTrueLove" regarding  https://github.com/ultramega/elementary/issues/27#issuecomment-332551938. I let them know that they are violating the license. I'll do the same for the other one if I don't hear back from Google. I don't have a lot of confidence that they will listen, though.

Thanks for all the work protecting the project.

**Comment by Poussinou** [comment]
@stevotvr I send a mail to [this association](https://framasoft.org/), the biggest one concerning free software in France. I hope they will have an idear to understand this, and maybe help us to come back to the old system, it was way better to fight libre licences violations...

**Comment by stevotvr** [comment]
Regarding https://github.com/ultramega/elementary/issues/27#issuecomment-331726466, the "author" has responded and agreed to add a link to this repository into the app.

**Comment by Poussinou** [comment]
Any news from Google about their answer to the last DMCA Request?

**Comment by stevotvr** [comment]
No, I haven't gotten any further responses from Google.
