### ISSUE TITLE
Electron Configuration Display

### ISSUE THREAD

**Issue by lufebe16** [ultramega/elementary#28]
d an f series take up to 10 resp. 14 electrons. The upperscript used displays the first digit only. So this results in a wrong count if there are more (2!) digits. E.g. Pb: [Xe] 4f14 5d10 6s2 6p2  instead of [Xe] 4f1 5d1 6s2 6p2.

**Comment by stevotvr** [comment]
Fixed in 0.8.4.

**Comment by lufebe16** [comment]
I just recognized that the new version 0.8.4 is available in google store. While I am waiting it to appear on f-droid. Is there any reason to not continue publishing with f-droid ?

**Comment by stevotvr** [comment]
It should be automatic. I'll look into it...

**Comment by stevotvr** [comment]
F-Droid wasn't able to build the app due to a missing repository. I added the repo and submitted a merge request a few days ago. So now we just have to wait for them to merge the changes and hopefully it will be able to build.

**Comment by stevotvr** [comment]
The changes were merged, so the update should be available on F-Droid soon.

**Comment by stevotvr** [comment]
It is now available on F-Droid. Thanks for bringing that to my attention.

**Comment by lufebe16** [comment]
On Mon, 02 Apr 2018 15:51:43 +0000 (UTC)
Steve Guidetti <notifications@github.com> wrote:

Thanks.

> It is now available on F-Droid. Thanks for bringing that to my attention.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ultramega/elementary/issues/28#issuecomment-377961141


--

**Comment by lufebe16** [comment]
On Mon, 02 Apr 2018 15:51:43 +0000 (UTC)
Steve Guidetti <notifications@github.com> wrote:

Thanks too for Your efforts.

> It is now available on F-Droid. Thanks for bringing that to my attention.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ultramega/elementary/issues/28#issuecomment-377961141


--
