### ISSUE TITLE
Position of La and Ac

### ISSUE THREAD

**Issue by Wolfram-Wolf** [ultramega/elementary#31]
Lanthanum and Actinium are part of the Group 3 elements. As such, they should not go in the separate block for the La and Ac series. This is also because La and Ac belong to the d-block (and not the f-block).

**Comment by stevotvr** [comment]
There seems to be some disagreement between sources whether they are included in the Lanthanides/Actinides series. I'm not sure what to do here. Do you have any other sources to justify moving those elements?

**Comment by Wolfram-Wolf** [comment]
La and Ac do belong to their respective series (and must be colour coded as such). However, they are d-block elements (and not f-block elements, as wrongly stated in the in-app description). Thus, they must be placed with other d-block elements in the 2 empty spaces, rather than in a separate block (the other elements in the f-block are fine). This positional discrepancy arises from the fact that we use the condensed form of the modern periodic table (and not the long form, which Wikipedia uses).

**Comment by Wolfram-Wolf** [comment]
The position of the elements must be as depicted here: https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Simple_Periodic_Table_Chart-en.svg/370px-Simple_Periodic_Table_Chart-en.svg.png

**Comment by Wolfram-Wolf** [comment]
The 'justification' for moving those elements is that they are d-block elements (and not f-block elements).

**Comment by stevotvr** [comment]
All of those elements belong in the 6th and 7th rows. The placeholders indicate which elements were removed. La and Ac were included in order to make room for the placeholders. This is the way I usually see the collapsed table presented in other sources.

**Comment by Wolfram-Wolf** [comment]
Not that it'd be wrong to do so. It's okay if the placeholders indicate the position of La and Ac.
