### ISSUE TITLE
Add isotopes relative abundance 

### ISSUE THREAD

**Issue by RGB-es** [ultramega/elementary#39]
Just a small feature request: to the end of the element details, there is a table showing the isotopes with their formula and atomic mass. It would be great to add to that table a third column with the relative abundance of those isotopes. 

Many thanks for this awesome app!

**Comment by stevotvr** [comment]
If someone collects and compiles the raw data required for this, I could implement this into the next version.

**Comment by RGB-es** [comment]
I found the following resources: 

https://www.nist.gov/pml/atomic-weights-and-isotopic-compositions-relative-atomic-masses

In that page it's possible to get isotope tables for all elements in several file formats (html, txt, etc.). The abundances ("isotopic composition") are normalized to 1.

Also:

http://moltensalt.org/references/static/downloads/pdf/stable-isotopes.pdf 

https://www.sisweb.com/referenc/source/exactmas.htm

Thank you again for this amazing app!

**Comment by stevotvr** [comment]
I added this here: 9edcc3028dc8ddb73e079d1902fee3c72c91efdc
Let me know if anything needs to be changed.

I actually had the data from the link you posted already parsed and loaded into my local database. I just never included it in the app.

**Comment by RGB-es** [comment]
> I added this here: [9edcc30](https://github.com/ultramega/elementary/commit/9edcc3028dc8ddb73e079d1902fee3c72c91efdc)
> Let me know if anything needs to be changed.
> 
> I actually had the data from the link you posted already parsed and loaded into my local database. I just never included it in the app.

I do not understand the code parts, but I checked the translated strings for Spanish and Italian. Spanish is perfect, but for Italian it should be "Abbondanza" (two "b"): the form "Abondanza" is considered archaic in modern Italian

https://www.dizionario-italiano.it/dizionario-italiano.php?parola=abbondanza

(one of the examples is precisely "abbondanza isotopica")

**Comment by stevotvr** [comment]
Thanks, I corrected the translation.
