### ISSUE TITLE
Options format

### ISSUE THREAD

**Issue by ghost** [ultramega/elementary#4]
If i use the app in table view, the options menu should be also open in "landscape format" - so you don't have to turn your phone/tablet 45°.

**Comment by ultramega** [comment]
What version of Android are you running?

**Comment by C4R2T3N** [comment]
5.1.1

**Comment by ghost** [comment]
5.1.1 on a Z3 Compact, but:

Found the problem, autoturn function of the display was disabled. If i turn it on it works. I think it would be nice if the options menu is always in landscape format if i have choosen the table view.

**Comment by ultramega** [comment]
Okay I've changed the activity to ignore the orientation of the device so the menu always shows in landscape mode.
