### ISSUE TITLE
German Wikipedia-Links

### ISSUE THREAD

**Issue by ghost** [ultramega/elementary#6]
Most of them are not working. Need help, i don't know how to correct these lines:

This works - english link:
`string name="wikiLang">en</string`
`<string name="wiki001">Hydrogen</string>`

This not:
`string name="wikiLang">de</string`
`<string name="wiki001">Hydrogen</string>`

This should be:
`string name="wikiLang">de</string`
`<string name="wiki001">Wasserstoff</string>`

Am i right?

**Comment by ultramega** [comment]
Yes, the URL to the Wikipedia page is https://de.wikipedia.org/wiki/Wasserstoff so it should be:
`<string name="wikiLang">de</string>`
`<string name="wiki001">Wasserstoff</string>`
